/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package jdbcConnect;

import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

/**
 *
 * @author DELL
 */
public class WelComePage extends HttpServlet {

    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>\n"
                    + "<html lang=\"en\" dir=\"ltr\">\n"
                    + "  <head>\n"
                    + "    <meta charset=\"UTF-8\" />\n"
                    + "    <title>Sticky Navigation Bar | CodingLab</title>\n"
                    + "    <style>\n"
                    + "      * {\n"
                    + "        margin: 0;\n"
                    + "        padding: 0;\n"
                    + "        box-sizing: border-box;\n"
                    + "        text-decoration: none;\n"
                    + "        font-family: \"Ubuntu\", sans-serif;\n"
                    + "      }\n"
                    + "      nav {\n"
                    + "        position: fixed;\n"
                    + "        top: 0;\n"
                    + "        left: 0;\n"
                    + "        width: 100%;\n"
                    + "        padding: 20px;\n"
                    + "        transition: all 0.4s ease;\n"
                    + "      }\n"
                    + "      nav.sticky {\n"
                    + "        padding: 15px 20px;\n"
                    + "        background: #4070f4;\n"
                    + "        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);\n"
                    + "      }\n"
                    + "      nav .nav-content {\n"
                    + "        height: 100%;\n"
                    + "        max-width: 1200px;\n"
                    + "        margin: auto;\n"
                    + "        display: flex;\n"
                    + "        align-items: center;\n"
                    + "        justify-content: space-between;\n"
                    + "      }\n"
                    + "      nav .logo a {\n"
                    + "        font-weight: 500;\n"
                    + "        font-size: 35px;\n"
                    + "        color: #4070f4;\n"
                    + "      }\n"
                    + "      nav.sticky .logo a {\n"
                    + "        color: #fff;\n"
                    + "      }\n"
                    + "      .nav-content .nav-links {\n"
                    + "        display: flex;\n"
                    + "      }\n"
                    + "      .nav-content .nav-links li {\n"
                    + "        list-style: none;\n"
                    + "        margin: 0 8px;\n"
                    + "      }\n"
                    + "      .nav-links li a {\n"
                    + "        text-decoration: none;\n"
                    + "        color: #0e2431;\n"
                    + "        font-size: 18px;\n"
                    + "        font-weight: 500;\n"
                    + "        padding: 10px 4px;\n"
                    + "        transition: all 0.3s ease;\n"
                    + "      }\n"
                    + "      .nav-links li a:hover {\n"
                    + "        color: #4070f4;\n"
                    + "      }\n"
                    + "      nav.sticky .nav-links li a {\n"
                    + "        color: #fff;\n"
                    + "        transition: all 0.4s ease;\n"
                    + "      }\n"
                    + "      nav.sticky .nav-links li a:hover {\n"
                    + "        color: #0e2431;\n"
                    + "      }\n"
                    + "      .home {\n"
                    + "        height: 100vh;\n"
                    + "        width: 100%;\n"
                    + "        background: url(\"images/background.png\") no-repeat;\n"
                    + "        background-size: cover;\n"
                    + "        background-position: center;\n"
                    + "        background-attachment: fixed;\n"
                    + "        font-family: \"Ubuntu\", sans-serif;\n"
                    + "      }\n"
                    + "      h2 {\n"
                    + "        font-size: 30px;\n"
                    + "        margin-bottom: 6px;\n"
                    + "        color: #4070f4;\n"
                    + "      }\n"
                    + "      .text {\n"
                    + "        text-align: justify;\n"
                    + "        padding: 40px 80px;\n"
                    + "        box-shadow: -5px 0 10px rgba(0, 0, 0, 0.1);\n"
                    + "      }\n"
                    + "      .header {\n"
                    + "        position: fixed;\n"
                    + "        top: 0;\n"
                    + "        left: 0;\n"
                    + "        width: 100%;\n"
                    + "      }\n"
                    + "      .navbar {\n"
                    + "        display: flex;\n"
                    + "        align-items: center;\n"
                    + "        justify-content: space-between;\n"
                    + "        max-width: 1200px;\n"
                    + "        margin: 0 auto;\n"
                    + "        padding: 20px 15px;\n"
                    + "      }\n"
                    + "      .navbar .logo a {\n"
                    + "        font-size: 1.8rem;\n"
                    + "        text-decoration: none;\n"
                    + "        color: #fff;\n"
                    + "      }\n"
                    + "      .navbar .links {\n"
                    + "        display: flex;\n"
                    + "        align-items: center;\n"
                    + "        list-style: none;\n"
                    + "        gap: 35px;\n"
                    + "      }\n"
                    + "      .navbar .links a {\n"
                    + "        font-weight: 500;\n"
                    + "        text-decoration: none;\n"
                    + "        color: #fff;\n"
                    + "        padding: 10px 0;\n"
                    + "        transition: 0.2s ease;\n"
                    + "      }\n"
                    + "      .navbar .links a:hover {\n"
                    + "        color: #47b2e4;\n"
                    + "      }\n"
                    + "      .navbar .buttons a {\n"
                    + "        text-decoration: none;\n"
                    + "        color: #fff;\n"
                    + "        font-size: 1rem;\n"
                    + "        padding: 15px 0;\n"
                    + "        transition: 0.2s ease;\n"
                    + "      }\n"
                    + "      .navbar .buttons a:not(:last-child) {\n"
                    + "        margin-right: 30px;\n"
                    + "      }\n"
                    + "      .navbar .buttons .signin:hover {\n"
                    + "        color: #47b2e4;\n"
                    + "      }\n"
                    + "      .navbar .buttons .signup {\n"
                    + "        border: 1px solid #fff;\n"
                    + "        padding: 10px 20px;\n"
                    + "        border-radius: 0.375rem;\n"
                    + "        text-align: center;\n"
                    + "        transition: 0.2s ease;\n"
                    + "      }\n"
                    + "      .navbar .buttons .signup:hover {\n"
                    + "        background-color: #47b2e4;\n"
                    + "        color: #fff;\n"
                    + "      }\n"
                    + "      .hero-section {\n"
                    + "        display: flex;\n"
                    + "        justify-content: space-evenly;\n"
                    + "        align-items: center;\n"
                    + "        height: 95vh;\n"
                    + "        padding: 0 15px;\n"
                    + "        max-width: 1200px;\n"
                    + "        margin: 0 auto;\n"
                    + "      }\n"
                    + "      .hero-section .hero {\n"
                    + "        max-width: 50%;\n"
                    + "        color: #fff;\n"
                    + "      }\n"
                    + "      .hero h2 {\n"
                    + "        font-size: 2.5rem;\n"
                    + "        margin-bottom: 20px;\n"
                    + "      }\n"
                    + "      .hero p {\n"
                    + "        font-size: 1.2rem;\n"
                    + "        margin-bottom: 20px;\n"
                    + "        color: #c9c7c7;\n"
                    + "      }\n"
                    + "      .hero-section .img img {\n"
                    + "        width: 517px;\n"
                    + "      }\n"
                    + "      .hero-section .buttons {\n"
                    + "        margin-top: 40px;\n"
                    + "      }\n"
                    + "      .hero-section .buttons a {\n"
                    + "        text-decoration: none;\n"
                    + "        color: #fff;\n"
                    + "        padding: 12px 24px;\n"
                    + "        border-radius: 0.375rem;\n"
                    + "        font-weight: 600;\n"
                    + "        transition: 0.2s ease;\n"
                    + "        display: inline-block;\n"
                    + "      }\n"
                    + "      .hero-section .buttons a:not(:last-child) {\n"
                    + "        margin-right: 15px;\n"
                    + "      }\n"
                    + "      .buttons .join {\n"
                    + "        background-color: #47b2e4;\n"
                    + "      }\n"
                    + "      .hero-section .buttons .learn {\n"
                    + "        border: 1px solid #fff;\n"
                    + "        border-radius: 0.375rem;\n"
                    + "      }\n"
                    + "      .hero-section .buttons a:hover {\n"
                    + "        background-color: #47b2e4;\n"
                    + "      }\n"
                    + "      /* Hamburger menu styles */\n"
                    + "      #menu-toggle {\n"
                    + "        display: none;\n"
                    + "      }\n"
                    + "      #hamburger-btn {\n"
                    + "        font-size: 1.8rem;\n"
                    + "        color: #fff;\n"
                    + "        cursor: pointer;\n"
                    + "        display: none;\n"
                    + "        order: 1;\n"
                    + "      }\n"
                    + "      @media screen and (max-width: 1023px) {\n"
                    + "        .navbar .logo a {\n"
                    + "          font-size: 1.5rem;\n"
                    + "        }\n"
                    + "        .links {\n"
                    + "          position: fixed;\n"
                    + "          left: -100%;\n"
                    + "          top: 75px;\n"
                    + "          width: 100%;\n"
                    + "          height: 100vh;\n"
                    + "          padding-top: 50px;\n"
                    + "          background: #175d69;\n"
                    + "          flex-direction: column;\n"
                    + "          transition: 0.3s ease;\n"
                    + "        }\n"
                    + "        .navbar #menu-toggle:checked ~ .links {\n"
                    + "          left: 0;\n"
                    + "        }\n"
                    + "        .navbar #hamburger-btn {\n"
                    + "          display: block;\n"
                    + "        }\n"
                    + "        .header .buttons {\n"
                    + "          display: none;\n"
                    + "        }\n"
                    + "        .hero-section .hero {\n"
                    + "          max-width: 100%;\n"
                    + "          text-align: center;\n"
                    + "        }\n"
                    + "        .hero-section img {\n"
                    + "          display: none;\n"
                    + "        }\n"
                    + "      }\n"
                    + "    </style>\n"
                    + "  </head>\n"
                    + "  <body>\n"
                    + "    <nav>\n"
                    + "      <div class=\"nav-content\">\n"
                    + "        <div class=\"logo\">\n"
                    + "          <a href=\"#\">Wellcome</a>\n"
                    + "        </div>\n"
                    + "        <ul class=\"nav-links\">\n"
                    + "          <li><a href=\"#\">Home</a></li>\n"
                    + "          <li><a href=\"#\">About</a></li>\n"
                    + "          <li><a href=\"#\">Skills</a></li>\n"
                    + "          <li><a href=\"#\">Services</a></li>\n"
                    + "          <li><a href=\"#\">Contact</a></li>\n"
                    + "        </ul>\n"
                    + "      </div>\n"
                    + "    </nav>\n"
                    + "\n"
                    + "    <section class=\"hero-section\">\n"
                    + "      <div class=\"hero\">\n"
                    + "        <h2>Mobile App Development</h2>\n"
                    + "        <p>\n"
                    + "          Join us in the exciting world of programming and turn your ideas into\n"
                    + "          reality. Unlock the world of endless possibilities - learn to code and\n"
                    + "          shape the digital future with us.\n"
                    + "        </p>\n"
                    + "        <div class=\"buttons\">\n"
                    + "          <a href='LoginPage' class=\"join\">Join Now</a>\n"
                    + "          <a href=\"#\" class=\"learn\">Learn More</a>\n"
                    + "        </div>\n"
                    + "      </div>\n"
                    + "      <div class=\"img\">\n"
                    + "        <img\n"
                    + "          src=\"https://www.codingnepalweb.com/demos/create-responsive-website-html-css/hero-bg.png\"\n"
                    + "          alt=\"hero image\"\n"
                    + "        />\n"
                    + "      </div>\n"
                    + "    </section>\n"
                    + "  </body>\n"
                    + "</html>");

        }
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}
