import java.util.Scanner;
class Project
{
    public static void main(String args[])
	{
		Scanner sc = new Scanner(System.in);
		
				System.out.println("\t+----------------------------------------------+");
				System.out.println("\t|--------------ASCII VALUE---------------------|");
				System.out.println("\t+----------------------------------------------+");
				System.out.println("\t|    CHARACTER            |    ASCII VALUE     |");
				System.out.println("\t|"+"       \\t"+"            |          9	     |");
                System.out.println("\t|"+"       \\n"+"            |         10	     |");
                System.out.println("\t|"+"       \\f"+"            |         12	     |");
                System.out.println("\t|"+"       \\r"+"            |         13	     |");
				System.out.println("\t|    Whitespace	        |         31	     |");
			    System.out.println("\t| 	 space	            |         32	     |");
			    System.out.println("\t| 	  !	                |         33	     |");
				System.out.println("\t|  	  \"                |         34	     |");
			    System.out.println("\t| 	  #                 |         35		 |");	
				System.out.println("\t|       $                 |	      36	     |");
				System.out.println("\t|		  %	                |         37	     |");
				System.out.println("\t|		  &                 |	      38	     |");
				System.out.println("\t|		  '	                |         39	     |");
				System.out.println("\t|		  (	                |         40	     |");
				System.out.println("\t|		  )	                |         41	     |");
				System.out.println("\t|	      *                 |	      42         |");
				System.out.println("\t|		  +	                |         43         |");
				System.out.println("\t|		  ,	                |         44		 |");
				System.out.println("\t|		  -	                |         45	     |");
				System.out.println("\t|		  .	                |         46	     |");
				System.out.println("\t|		  /	                |         47	     |");
				System.out.println("\t|		  0                	|         48	     |");
				System.out.println("\t|		  1	                |         49	     |");
				System.out.println("\t|		  2              	|         50	     |");
				System.out.println("\t|       3	                |         51         |");
				System.out.println("\t|       4	                |         52	     |");
				System.out.println("\t|		  5	                |         53	     |");
				System.out.println("\t|		  6             	|         54	     |");
				System.out.println("\t|		  7					|		  55	     |");	
				System.out.println("\t|		  8	                |         56	     |");
				System.out.println("\t|		  9              	|         57	     |");
				System.out.println("\t|		  :	                |         58	     |");
				System.out.println("\t|		  ;	                |         59	     |");
				System.out.println("\t|		  <	                |         60	     |");
				System.out.println("\t|		  =					|		  61	     |");
				System.out.println("\t|		  >					|         62	     |");
				System.out.println("\t|		  ?					|		  63	     |");
				System.out.println("\t|		  @	        		| 		  64	     |");
				System.out.println("\t|		  A 			    |		  65	     |");
				System.out.println("\t|		  B					| 		  66	     |");
				System.out.println("\t|		  C					|		  67	     |");
				System.out.println("\t|		  D					|		  68	     |");
				System.out.println("\t|		  E					|		  69	     |");
				System.out.println("\t|		  F					|		  70	     |");
				System.out.println("\t|		  G	     			|		  71	     |");
				System.out.println("\t|		  H					|		  72	     |");
				System.out.println("\t|		  I					|		  73	     |");
				System.out.println("\t|		  J					|		  74	     |");
				System.out.println("\t|		  K					| 		  75	     |");
				System.out.println("\t|		  L					|		  76	     |");
				System.out.println("\t|		  M				 	|		  77	     |");
				System.out.println("\t|		  N					|		  78	     |");
				System.out.println("\t|		  O					|		  79	     |");
				System.out.println("\t|		  P					|		  80	     |");
				System.out.println("\t|		  Q	  				|		  81	     |");
				System.out.println("\t|		  R					|		  82	     |");
				System.out.println("\t|		  S	   				|		  83	     |");
				System.out.println("\t|		  T					|		  84	     |");
				System.out.println("\t|		  U					|		  85	     |");
				System.out.println("\t|		  V 				|		  86	     |");
				System.out.println("\t|		  W					|		  87	     |");
				System.out.println("\t|		  X					|		  88	     |");
				System.out.println("\t|		  Y					|	 	  89	     |");
				System.out.println("\t|		  Z					|		  90	     |");
				System.out.println("\t|		  [					|		  91	     |");
				sSystem.out.println("\t|	  \\			    |		  92	     |");
				System.out.println("\t|		  ]					|		  93	     |");
				System.out.println("\t|		  ^					|		  94	     |");
				System.out.println("\t|		  _					|		  95	     |");
				System.out.println("\t|		  `					|		  96	     |");
				System.out.println("\t|		  a					|		  97	     |");
				System.out.println("\t|		  b					|		  98	     |");
				System.out.println("\t|		  c					|		  99	     |");
				System.out.println("\t|		  d					|		 100	     |");
				System.out.println("\t|		  e					|		 101	     |");
				System.out.println("\t|		  f					|		 102	     |");
				System.out.println("\t|		  g					|		 103	     |");
				System.out.println("\t|		  h					|		 104	     |");
				System.out.println("\t|		  i					|		 105	     |");
				System.out.println("\t|		  j					|		 106	     |");
				System.out.println("\t|		  k					|		 107	     |");
				System.out.println("\t|		  l					|		 108	     |");
				System.out.println("\t|		  m					|		 109	     |");
				System.out.println("\t|		  n					|		 110	     |");
				System.out.println("\t|		  o					|		 111         |");	
				System.out.println("\t|		  p					|		 112	     |");
				System.out.println("\t|		  q					|		 113	     |");
				System.out.println("\t|		  r					|		 114	     |");
				System.out.println("\t|		  s					|		 115	     |");
				System.out.println("\t|		  t					|		 116	     |");
				System.out.println("\t|		  u					|		 117	     |");
				System.out.println("\t|		  v					|		 118	     |");
				System.out.println("\t|		  w					|		 119	     |");
				System.out.println("\t|		  x					|		 120	     |");
				System.out.println("\t|		  y	    			|		 121	     |");
				System.out.println("\t|		  z					|		 122	     |");
				System.out.println("\t|		  {					|		 123	     |");
				System.out.println("\t|  	  |			        |		 124	     |");
				System.out.println("\t|		  }					|		 125	     |");
				System.out.println("\t|		  ~	  				|		 126	     |");
				System.out.println("\t+----------------------------------------------+");
	}
}